apiVersion: v1
kind: Secret
metadata:
  name: rtc-turn-tls
  namespace: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_CERT
    -----END CERTIFICATE-----
  tls.key: |-
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY
    -----END PRIVATE KEY-----
