apiVersion: v1
kind: Secret
metadata:
  name: rtc-turn-secret
  namespace: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
type: Opaque
stringData:
  TURN_SHARED_SECRET: replace-with-strong-random-secret
