apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtc-ingress
  namespace: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/upstream-hash-by: '$remote_addr'
    nginx.ingress.kubernetes.io/proxy-body-size: '8m'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.example.com
        - api.example.com
        - signal.example.com
      secretName: rtc-platform-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
    - host: signal.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signaling
                port:
                  name: http
