apiVersion: v1
kind: Secret
metadata:
  name: rtc-mediasoup-secret
  namespace: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
type: Opaque
stringData:
  LOG_LEVEL: info
  NODE_ENV: production
