apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mediasoup-hpa
  namespace: rtc-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediasoup
  minReplicas: 3
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
