apiVersion: v1
kind: Namespace
metadata:
  name: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
