apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rtc-data
  labels:
    app.kubernetes.io/part-of: rtc-platform
type: Opaque
stringData:
  POSTGRES_DB: rtc
  POSTGRES_USER: rtc
  POSTGRES_PASSWORD: change-me
