apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rtc-data
  labels:
    app: postgres
    app.kubernetes.io/part-of: rtc-platform
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres
