apiVersion: v1
kind: Secret
metadata:
  name: rtc-app-secret
  namespace: rtc-apps
  labels:
    app.kubernetes.io/part-of: rtc-platform
type: Opaque
stringData:
  REDIS_URL: redis://redis.rtc-data.svc.cluster.local:6379
  DATABASE_URL: postgresql://rtc:change-me@postgres.rtc-data.svc.cluster.local:5432/rtc
