apiVersion: v1
kind: Service
metadata:
  name: signaling
  namespace: rtc-apps
  labels:
    app: signaling
    app.kubernetes.io/part-of: rtc-platform
spec:
  type: ClusterIP
  selector:
    app: signaling
  ports:
    - name: http
      protocol: TCP
      port: 4010
      targetPort: http
